module.exports = Object.freeze({
  TRANSFER: "TRANSFER",
  WITHDRAW: "WITHDRAW",
  DEPOSIT: "DEPOSIT",
  STAKE: "STAKE",
  UN_STAKE: "UN_STAKE",
  EXCHANGE: "EXCHANGE",
  BANKTTRANSFER: "BANKTTRANSFER",
  TRADING: "TRADING",
  SUBSCRIPTION:"SUBSCRIPTION"


});
